#ifndef MOD_PYTHON_ENGINE_ACCOUNT_HOOK_H
#define MOD_PYTHON_ENGINE_ACCOUNT_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace Account
    {
        DEFINE_GAME_HOOK(ACCOUNT, ON_ACCOUNT_LOGIN, 0)
        DEFINE_GAME_HOOK(ACCOUNT, ON_BEFORE_ACCOUNT_DELETE, 1)
        DEFINE_GAME_HOOK(ACCOUNT, ON_LAST_IP_UPDATE, 2)
        DEFINE_GAME_HOOK(ACCOUNT, ON_FAILED_ACCOUNT_LOGIN, 3)
        DEFINE_GAME_HOOK(ACCOUNT, ON_EMAIL_CHANGE, 4)
        DEFINE_GAME_HOOK(ACCOUNT, ON_FAILED_EMAIL_CHANGE, 5)
        DEFINE_GAME_HOOK(ACCOUNT, ON_PASSWORD_CHANGE, 6)
        DEFINE_GAME_HOOK(ACCOUNT, ON_FAILED_PASSWORD_CHANGE, 7)
        DEFINE_GAME_HOOK(ACCOUNT, CAN_ACCOUNT_CREATE_CHARACTER, 8)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_ACCOUNT_HOOK_H