#ifndef MOD_PYTHON_ENGINE_ACHIEVEMENT_HOOK_H
#define MOD_PYTHON_ENGINE_ACHIEVEMENT_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace Achievement
    {
        DEFINE_GAME_HOOK(ACHIEVEMENT, SET_REALM_COMPLETED, 0)
        DEFINE_GAME_HOOK(ACHIEVEMENT, IS_COMPLETED_CRITERIA, 1)
        DEFINE_GAME_HOOK(ACHIEVEMENT, IS_REALM_COMPLETED, 2)
        DEFINE_GAME_HOOK(ACHIEVEMENT, ON_BEFORE_CHECK_CRITERIA, 3)
        DEFINE_GAME_HOOK(ACHIEVEMENT, CAN_CHECK_CRITERIA, 4)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_ACHIEVEMENT_HOOK_H