#ifndef MOD_PYTHON_ENGINE_ARENATEAM_HOOK_H
#define MOD_PYTHON_ENGINE_ARENATEAM_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace ArenaTeam
    {
        DEFINE_GAME_HOOK(ARENATEAM, ON_GET_SLOT_BY_TYPE, 0)
        DEFINE_GAME_HOOK(ARENATEAM, ON_GET_ARENA_POINTS, 1)
        DEFINE_GAME_HOOK(ARENATEAM, ON_TYPEID_TO_QUEUEID, 2)
        DEFINE_GAME_HOOK(ARENATEAM, ON_QUEUEID_TO_ARENA_TYPE, 3)
        DEFINE_GAME_HOOK(ARENATEAM, ON_SET_ARENA_MAX_PLAYERS_PER_TEAM, 4)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_ARENATEAM_HOOK_H