#ifndef MOD_PYTHON_ENGINE_ARENA_HOOK_H
#define MOD_PYTHON_ENGINE_ARENA_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace Arena
    {
        DEFINE_GAME_HOOK(ARENA, CAN_ADD_MEMBER, 0)
        DEFINE_GAME_HOOK(ARENA, ON_GET_POINTS, 1)
        DEFINE_GAME_HOOK(ARENA, CAN_SAVE_TO_DB, 2)
        DEFINE_GAME_HOOK(ARENA, ON_BEFORE_CHECK_WIN_CONDITION, 3)
        DEFINE_GAME_HOOK(ARENA, ON_ARENA_START, 4)
        DEFINE_GAME_HOOK(ARENA, ON_BEFORE_TEAM_MEMBER_UPDATE, 5)
        DEFINE_GAME_HOOK(ARENA, CAN_SAVE_ARENA_STATS_FOR_MEMBER, 6)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_ARENA_HOOK_H