#ifndef MOD_PYTHON_ENGINE_CREATURE_HOOK_H
#define MOD_PYTHON_ENGINE_CREATURE_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace Creature
    {
        DEFINE_GAME_HOOK(CREATURE, ON_GOSSIP_HELLO, 0)
        DEFINE_GAME_HOOK(CREATURE, ON_GOSSIP_SELECT, 1)
        DEFINE_GAME_HOOK(CREATURE, ON_GOSSIP_SELECT_CODE, 2)
        DEFINE_GAME_HOOK(CREATURE, ON_QUEST_ACCEPT, 3)
        DEFINE_GAME_HOOK(CREATURE, ON_QUEST_SELECT, 4)
        DEFINE_GAME_HOOK(CREATURE, ON_QUEST_COMPLETE, 5)
        DEFINE_GAME_HOOK(CREATURE, ON_QUEST_REWARD, 6)
        DEFINE_GAME_HOOK(CREATURE, ON_ADD_WORLD, 7)
        DEFINE_GAME_HOOK(CREATURE, ON_REMOVE_WORLD, 8)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_CREATURE_HOOK_H