#ifndef MOD_PYTHON_ENGINE_GAMEOBJECT_HOOK_H
#define MOD_PYTHON_ENGINE_GAMEOBJECT_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace GameObject
    {
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_GOSSIP_HELLO, 0)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_GOSSIP_SELECT, 1)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_GOSSIP_SELECT_CODE, 2)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_QUEST_ACCEPT, 3)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_QUEST_REWARD, 4)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_DESTROYED, 5)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_DAMAGED, 6)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_MODIFY_HEALTH, 7)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_LOOT_STATE_CHANGED, 8)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_UPDATE, 9)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_ADD_WORLD, 10)
        DEFINE_GAME_HOOK(GAMEOBJECT, ON_REMOVE_WORLD, 11)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_GAMEOBJECT_HOOK_H