#ifndef MOD_PYTHON_ENGINE_SERVER_HOOK_H
#define MOD_PYTHON_ENGINE_SERVER_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace Server
    {
        DEFINE_GAME_HOOK(SERVER, ON_NETWORK_START, 0)
        DEFINE_GAME_HOOK(SERVER, ON_NETWORK_STOP, 1)
        DEFINE_GAME_HOOK(SERVER, ON_SOCKET_OPEN, 2)
        DEFINE_GAME_HOOK(SERVER, ON_SOCKET_CLOSE, 3)
        DEFINE_GAME_HOOK(SERVER, CAN_PACKET_SEND, 4)
        DEFINE_GAME_HOOK(SERVER, CAN_PACKET_RECEIVE, 5)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_SERVER_HOOK_H