#ifndef MOD_PYTHON_ENGINE_UNIT_HOOK_H
#define MOD_PYTHON_ENGINE_UNIT_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace Unit
    {
        DEFINE_GAME_HOOK(UNIT, ON_HEAL, 0)
        DEFINE_GAME_HOOK(UNIT, ON_DAMAGE, 1)
        DEFINE_GAME_HOOK(UNIT, MODIFY_PERIODIC_DAMAGE_AURAS_TICK, 2)
        DEFINE_GAME_HOOK(UNIT, MODIFY_MELEE_DAMAGE, 3)
        DEFINE_GAME_HOOK(UNIT, MODIFY_SPELL_DAMAGE_TAKEN, 4)
        DEFINE_GAME_HOOK(UNIT, MODIFY_HEAL_RECEIVED, 5)
        DEFINE_GAME_HOOK(UNIT, ON_BEFORE_ROLL_MELEE_OUTCOME_AGAINST, 6)
        DEFINE_GAME_HOOK(UNIT, ON_AURA_APPLY, 7)
        DEFINE_GAME_HOOK(UNIT, ON_AURA_REMOVE, 8)
        DEFINE_GAME_HOOK(UNIT, IF_NORMAL_REACTION, 9)
        DEFINE_GAME_HOOK(UNIT, CAN_SET_PHASE_MASK, 10)
        DEFINE_GAME_HOOK(UNIT, IS_CUSTOM_BUILD_VALUES_UPDATE, 11)
        DEFINE_GAME_HOOK(UNIT, SHOULD_TRACK_VALUES_UPDATE_POS_BY_INDEX, 12)
        DEFINE_GAME_HOOK(UNIT, ON_PATCH_VALUES_UPDATE, 13)
        DEFINE_GAME_HOOK(UNIT, ON_UNIT_UPDATE, 14)
        DEFINE_GAME_HOOK(UNIT, ON_DISPLAYID_CHANGE, 15)
        DEFINE_GAME_HOOK(UNIT, ON_UNIT_ENTER_EVADE_MODE, 16)
        DEFINE_GAME_HOOK(UNIT, ON_UNIT_ENTER_COMBAT, 17)
        DEFINE_GAME_HOOK(UNIT, ON_UNIT_DEATH, 18)
        DEFINE_GAME_HOOK(UNIT, ON_UNIT_SET_SHAPESHIFT_FORM, 19)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_UNIT_HOOK_H