#ifndef MOD_PYTHON_ENGINE_WORLD_HOOK_H
#define MOD_PYTHON_ENGINE_WORLD_HOOK_H

#include "HookRegistry.h"

namespace PyEng::Hooks
{
    namespace World
    {
        DEFINE_GAME_HOOK(WORLD, ON_OPEN_STATE_CHANGE, 0)
        DEFINE_GAME_HOOK(WORLD, ON_AFTER_CONFIG_LOAD, 1)
        DEFINE_GAME_HOOK(WORLD, ON_LOAD_CUSTOM_DATABASE_TABLE, 2)
        DEFINE_GAME_HOOK(WORLD, ON_BEFORE_CONFIG_LOAD, 3)
        DEFINE_GAME_HOOK(WORLD, ON_MOTD_CHANGE, 4)
        DEFINE_GAME_HOOK(WORLD, ON_SHUTDOWN_INITIATE, 5)
        DEFINE_GAME_HOOK(WORLD, ON_SHUTDOWN_CANCEL, 6)
        DEFINE_GAME_HOOK(WORLD, ON_UPDATE, 7)
        DEFINE_GAME_HOOK(WORLD, ON_STARTUP, 8)
        DEFINE_GAME_HOOK(WORLD, ON_SHUTDOWN, 9)
        DEFINE_GAME_HOOK(WORLD, ON_AFTER_UNLOAD_ALL_MAPS, 10)
        DEFINE_GAME_HOOK(WORLD, ON_BEFORE_FINALIZE_PLAYER_WORLD_SESSION, 11)
        DEFINE_GAME_HOOK(WORLD, ON_BEFORE_WORLD_INITIALIZED, 12)
    }

} // namespace PyEng::Hooks

#endif // MOD_PYTHON_ENGINE_WORLD_HOOK_H